# Generated by Django 4.2.5 on 2023-09-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Номер телефона в формате 7XXXXXXXXXX', max_length=12, unique=True)),
                ('mobile_operator_code', models.CharField(help_text='Код мобильного оператора', max_length=5)),
                ('tag', models.CharField(help_text='Произвольная метка', max_length=255)),
                ('timezone', models.CharField(help_text='Часовой пояс', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(help_text='Дата и время запуска рассылки')),
                ('end_datetime', models.DateTimeField(help_text='Дата и время окончания рассылки')),
                ('message_text', models.TextField(help_text='Текст сообщения для доставки клиенту')),
                ('client_filter_mobile_operator', models.CharField(help_text='Код мобильного оператора для фильтрации клиентов', max_length=5)),
                ('client_filter_tag', models.CharField(help_text='Тег для фильтрации клиентов', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания сообщения')),
                ('status', models.CharField(help_text='Статус отправки', max_length=50)),
                ('client', models.ForeignKey(help_text='Клиент, которому отправили', on_delete=django.db.models.deletion.CASCADE, to='mailings.client')),
                ('mailing', models.ForeignKey(help_text='Рассылка, в рамках которой было отправлено сообщение', on_delete=django.db.models.deletion.CASCADE, to='mailings.mailing')),
            ],
        ),
    ]
